---
- name: 'Vault PKI | Fetch certificate if exist'
  uri:
    url:         '{{ vault_addr }}/v1/secret/data/{{ cert_vault_storing_path | mandatory }}'
    method:      'GET'
    headers:     '{{ certs_vault_headers }}'
    ca_path:     '{{ cert_vault_ca_path }}'
    client_cert: '{{ cert_vault_client_cert_path }}'
    client_key:  '{{ cert_vault_client_key_path }}'
    status_code: [200, 404]
  register: response

- set_fact:
    certificate: '{{ response.json.data.data.certificate }}'
    private_key: '{{ response.json.data.data.private_key }}'
      #no_log: true
  when: response.status == 200

- set_fact:
    cert_existing: '{{ response.status == 200 }}'
