---
- name: 'Vault PKI | Generating CSR for Application CA'
  uri:
    url: '{{ vault_addr }}/v1/{{ vault_pki_engine }}/intermediate/generate/exported'
    method: 'POST'
    return_content: yes
    headers: '{{ certs_vault_headers }}'
    body:
      common_name:  '{{ cert_common_name | mandatory }}'
      issuer_name:  '{{ cert_ca_issuer_name | mandatory }}'
      key_name:     '{{ cert_ca_issuer_name | mandatory }}'
      organization: '{{ cert_info.organization }}'
      ou:           '{{ cert_info.unit }}'
      country: '{{ cert_info.country }}'
      ttl: '{{ cert_ca_ttl }}'
    body_format: 'json'
    ca_path: '{{ cert_vault_ca_path }}'
    client_cert: '{{ cert_vault_client_cert_path }}'
    client_key: '{{ cert_vault_client_key_path }}'
  register: response_csr

- name: 'Vault PKI | Signing the certificate'
  uri:
    url: '{{ vault_addr }}/v1/pki/root/sign-intermediate'
    method:  'POST'
    return_content: yes
    headers: '{{ certs_vault_headers }}'
    body:
        common_name: '{{ cert_common_name | mandatory }}'
        organization: '{{ cert_info.organization }}'
        ou: '{{ cert_info.unit }}'
        country: '{{ cert_info.country }}'
        ttl: '{{ cert_ca_ttl }}'
        csr: '{{ response_csr.json.data.csr }}'
    body_format: 'json'
    ca_path: '{{ cert_vault_ca_path }}'
    client_cert: '{{ cert_vault_client_cert_path }}'
    client_key: '{{ cert_vault_client_key_path }}'
  register: response_signing

- name: 'Debug'
  debug:
    msg: '{{ response_signing.json }}'

- name: 'Vault PKI | Loading the Application CA'
  uri:
    url: '{{ vault_addr }}/v1/{{ vault_pki_engine }}/intermediate/set-signed'
    method:  'POST'
    return_content: yes
    headers: '{{ certs_vault_headers }}'
    body:
      certificate: '{{ response_signing.json.data.certificate }}'
    body_format: 'json'
    ca_path: '{{ cert_vault_ca_path }}'
    client_cert: '{{ cert_vault_client_cert_path }}'
    client_key: '{{ cert_vault_client_key_path }}'

- set_fact:
    certificate: '{{ response_signing.json.data.certificate }}'
    private_key: '{{ response_csr.json.data.private_key }}'
  no_log: true
